services:

  mongodb:
    image: mongo:8

    container_name: spinx-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: spinx

    volumes:
      - mongo-data:/data/db

volumes:

  mongo-data: